# Generated by Django 6.1 on 2026-09-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('technicians', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='technicians',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='technicians.technicians'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='tickets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.tickets'),
        ),
    ]
